### ISSUE TITLE
Feature Request: disable Image Cache based on regex

### ISSUE THREAD

**Issue by rucciva** [enix/kube-image-keeper#103]
Hi, thank you very much for creating this tools. it is very useful,

Though i'm having a bit of a hiccup when using this tools with pod that is watched by [argocd-image-updater](https://argocd-image-updater.readthedocs.io/en/stable/). The pod is currently consists of multiple containers, with a mix of  public image and internally-developed docker image. The argocd-image-updater is set to automatically update the pod when the internally-developed docker image is updated. But when kube-image-keeper is used, the internally-developed docker-image is no longer recognized by argocd-image-updater. I surely can ignore this pod, but this also means that the public image won't be cached (which is the one that usually takes longer to download). 

So, it will be more awesome if there is some regex based mechanism to ignore images to be cached, maybe by defining the regex on annotations.

**Comment by rucciva** [comment]
Hi Maintainers, will pull request accepted for this, i think i can work on this

**Comment by paullaffitte** [comment]
Hello,

A pull request would be very appreciated thanks. If you want to work on it, I think you could implement it in `func (a *ImageRewriter) handleContainer` in `pod_webhook.go`. For the list of regex, please create a value `controllers.webhook.ignoredImages`. Since we already have a value `controllers.webhook.ignoredNamespace`, it makes sense to reuse the same format for ignoring images.

**Comment by rucciva** [comment]
Hi @paullaffitte , any feedback on the PR?
Thanks
