### ISSUE TITLE
Registry lock not released after a garbage collection job error

### ISSUE THREAD

**Issue by genseb13011** [enix/kube-image-keeper#209]
Hi,

I've faced an issue following a garbage collection job error.

**Error**
The images weren't cached anymore.
The error was: _Failed to cache image {IMAGE_NAME} unexpected status code 405 Method Not Allowed: Method not allowed_

**Cause**
The garbage collection job lock the registry (read only) at the end of its process (_kubectl set env deploy kube-image-keeper-registry REGISTRY_STORAGE_MAINTENANCE_READONLY="{\"enabled\":true}"_)
The garbage collection job failed with following error: _failed to garbage collect: failed to mark: s3aws: s3aws: failed to retrieve tags unknown repository name={IMAGE_NAME} terminate_
The job stopped and never run the last command which release the repository lock (_kubectl set env deploy kube-image-keeper-registry REGISTRY_STORAGE_MAINTENANCE_READONLY-)_

**Evolution**
The job should release the lock before be killed.

**Comment by Nicolasgouze** [comment]
Hello @genseb13011, 

Thanks for your feedbacks.
Can you please give us as many information as possible regarding your setup, so that we can investigate and the root cause for the GC failure ? (Cluster distribution, version, main components, image we can use to reproduce the issue  …)
 
We already faced such 405 errors after GC issues. 
You’re right, we unfortunately do not yet remove the registry lock in such situations.  
See #124 for example. We also face the same situation when the registry is empty + the GC starts …
  
As a work-around, I propose you to set --deleteUntagged attribute to false. In you situation, it should help ! 

As a short term, in order to limitate the GC issues impacts we plan to : 
1-  Force the exit from readonly mode
2- Put in place a metric so that you can follow GC issues !
