### ISSUE TITLE
[Question] Best practicies of usage that keeper for multitenancy cluster

### ISSUE THREAD

**Issue by gonchik** [enix/kube-image-keeper#221]
Hello! 
Can you please tell me about the best practices?
Currently, we have started installing new clusters (multitenancy) on hardware where there are no statefull apps and dedicated storage.
And I would like to understand how you solve these problems?
since image caches on clusters are stateful.

P.S. I serve Gitlab Registry and our k8s engineers that kube-image-keeper is not help for the situation once our Gitlab registry is not helpful once registry is down.

Cheers,
GT

**Comment by paullaffitte** [comment]
Hello,

Kuik doesn't support multi-tenancy for now, but we are currently thinking about a solution to support it. I will keep you updated when a solution is found.

**Comment by Nicolasgouze** [comment]
Hi @gonchik , 

As highlighted by @paullaffitte , we've been thinking on a solution in order to manage your use case (we also had other scenario in mind) BUT unfortunately until now did not find anything satysfying !
With the design approaches we tryied, we felt like we were not anymore in agreement with the initial « kuik promises » :
- Keep it simple, secure
- Easiness to understand & deploy    
I’ll come back to you if we change our plan. 
Out of curiosity, did you tried to use a stand-alone registry & configure it as a mirror (updating containerd config) ?

**Comment by Nicolasgouze** [comment]
Hi, closing this issue in agreement with my previous comment.
