### ISSUE TITLE
[Question] - Additional pull secret

### ISSUE THREAD

**Issue by a-chartier** [enix/kube-image-keeper#265]
Good Morning,

I am have what is hopefully a quick question / request, I am wondering if it is possible to provide an additional pull secret that is used as another possible credential on-top of whatever is located within the given manifest.

Just for some context I am testing this out on OpenShift which has a number of internal pods which I would like to cache internally but the secret for them is provided at the CRI-O pod level instead of on the actual deployment spec. 

So ideally  whatever `global` secret is provided into the Helm chart could simply be appended into the `cachedImage.Spec.PullSecretNames` slice

**Comment by paullaffitte** [comment]
Hello,

Do your pods are using a `ServiceAccount`? If so, you could provide the secret at the `ServiceAccount` level. Otherwise you could also edit each `CachedImage` to manually add required pull secrets.

We will, in the next weeks, release a new version that will introduce a `Repository` CRD, pull secrets will then be handled at the `Repository` level. I hope it will make it easier to manually provide custom pull secrets.

I hope those solution will help you, for now we don't plan to implement global pull secrets at chart level. I'm closing the issue but feel free to re-open it if none of the proposed solutions works for you.

**Comment by a-chartier** [comment]
@paullaffitte 

Thanks for the response.  These ones in particular are not using a `ServiceAccount` token. It's similar to how `containerD` can have registry auth defined right at the CNI level.

I will keep an eye out for the new version and see if the `Repository` CRD helps in this situation, looking at the current commit's made I suspect it will.

Thanks for such a useful project.
