### ISSUE TITLE
Configure CacheImages Resources to Default to Retain Images via Configuration

### ISSUE THREAD

**Issue by csc-piscopo** [enix/kube-image-keeper#363]
Hi team,

I hope you're all doing well!

I wanted to propose an enhancement regarding the CacheImages resources. Specifically, I was wondering if there would be any appetite for configuring these resources to default to retaining images via a configuration setting.

This adjustment could be particularly beneficial in scale-to-zero scenarios, where pods are being removed along with their container images. By defaulting to retain images, we can improve startup times and overall performance when scaling back up, as the images will already be cached. This would reduce the overhead and latency associated with pulling images from the registry each time a pod is recreated.

Looking forward to hearing your thoughts on this idea!

**Comment by paullaffitte** [comment]
Hello,

You can configure the `.cachedImagesExpiryDelay` (in days) value from the helm chart. This way, images will be kept in cache for the given duration. The was implemented specifically for scale-to-zero scenarios. You could also write a script to add the retain flag on some images or write a kyverno policy.

Does one of this solution could solve your issue? Could you explain why if it doesn't? IMHO it's a good thing that images eventually expires in order to free up space.

Thanks!
