### ISSUE TITLE
Pull images that needs cached from Kubernetes nodes (images cached by CRI) instead of pulling images from remote registry.

### ISSUE THREAD

**Issue by sivarama-p-raju** [enix/kube-image-keeper#404]
Hi Team,

First of all, thanks a lot for "kube-image-keeper". It is a great project and solves many problems for me.

I would like to request for a feature, which could help the project.

When images need cached to the "kube-image-keeper's registry, the images are pulled from remote image registry.

Would it be possible to query the local cache on the nodes first to check if they already have the image ? If they do, then the image could be pulled from there instead of the remote registry.

We have a use-case where we only save 10 tags of a repository on our remote registry. However, one or more of our kubernetes clusters could be running a deployment using an image tag that is no longer present in the remote registry.

In such a case, the caching fails since it is not present on the remote registry:

```
$ kubectl get cachedimages
NAME                                                                STATUS         CACHED   RETAIN   EXPIRES AT   PODS COUNT   AGE
<repository>-<tag>                                                 ErrImagePull                                       6        95m
```

Since the image with the needed tag is already cached on at least one of the nodes in the cluster, it would make sense to pull it from there.

This could also help reduce the traffic with the remote registry for all the image pulls.

Could you please review and let me know your thoughts on the same ?

Thanks and regards,
Sivarama Raju P

**Comment by sivarama-p-raju** [comment]
Hi Team,

Could you please let me know if you have any thoughts regarding my idea ?

Thanks in advance.

**Comment by Nicolasgouze** [comment]
Hi @sivarama-p-raju,

First of all,  thanks for your feedback & sorry to come back so lately to you. 
This is a feature we talked about internally a couple of months back, so I think I fully get your point. :)

The final statement was that we do not want to complexify the product having two different retrieval scenario. 

Nevertheless, have a look at the "cachedimages" CustomResource (and more precisely the "retain" & "expires at" parameters you can see in your logs). You have here the possibility to set the : 

- "retain" flag so that you can always keep the last version of an image:tag. 
- "expires at" can be used in order to extend the cached image validity so that it's not removed by the GC process

It needs a bit of complementary work on your end if you want to "industrialize", but it should definitely help you ! 

NB : almost sure

**Comment by sivarama-p-raju** [comment]
Hi @Nicolasgouze 
Thanks a lot for your reply and sorry for not responding earlier.

I fully agree with your reasoning behind your decision.

Thanks again for looking into this.
